/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef BIVARIATEGAUS
#define BIVARIATEGAUS

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class bivariateGaus : public RooAbsPdf {
public:
  bivariateGaus() {} ; 
  bivariateGaus(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _y,
	      RooAbsReal& _px,
	      RooAbsReal& _sx,
	      RooAbsReal& _py,
	      RooAbsReal& _sy,
	      RooAbsReal& _r);
  bivariateGaus(const bivariateGaus& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new bivariateGaus(*this,newname); }
  inline virtual ~bivariateGaus() { }

protected:

  RooRealProxy x ;
  RooRealProxy y ;
  RooRealProxy px ;
  RooRealProxy sx ;
  RooRealProxy py ;
  RooRealProxy sy ;
  RooRealProxy r ;
  
  Double_t evaluate() const ;

private:

  ClassDef(bivariateGaus,1) // Your description goes here...
};
 
#endif
